env:
  ASAN_OPTIONS: 'abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1:log_path=./log/asan.log'
  ASAN_SYMBOLIZER_PATH: ./tools/llvm-symbolizer
config:
  production_mode: false
  # datafile_disk_percentage: '50'
  datafile_size: '2G'
  datafile_next: '2G'
  datafile_maxsize: '50G'
  # log_disk_percentage: '10'
  log_disk_size: '10G'
  memory_limit: '2G'
  system_memory: '1G'
  cpu_count: '8'
  workers_per_cpu_quota: '10'
  schema_history_expire_time: '1d'
  net_thread_count: '4'
